language: node_js
node_js:
    - "8"

branches:
  only:
    - blog

before_install:
    - npm install -g hexo-cli

install:
    - npm install

before_script:
    - git config --global user.name 'xcnick'
    - git config --global user.email 'xcnick0412@gmail.com'
    - git submodule update --init --recursive
    - sed -i 's/(\[\\\\/(\[/' ./node_modules/marked/lib/marked.js

script:
    - hexo generate --config ./source/_data/next.yml

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  on:
    branch: master