language: node_js
node_js:
    - "10"

branches:
  only:
    - blog

before_install:
    - npm install -g hexo-cli

install:
    - npm install

before_script:
    - git config --global user.name 'xcnick'
    - git config --global user.email 'xcnick0412@gmail.com'
    - git submodule update --init --recursive
    - sed -i 's/(\[\\\\/(\[/' ./node_modules/marked/lib/marked.js

script:
    - hexo generate --config ./source/_data/next.yml
    - sed -i'' "/^ *repo/s~github\.com~${GITHUB_TOKEN}@github.com~" ./source/_data/next.yml
    - hexo deploy --config ./source/_data/next.yml